/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useControls } from "leva";

export const Enemy = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "./models/enemies/Enemy.glb"
  );
  const { actions } = useAnimations(animations, group);

  const { animation } = useControls({
    animation: {
      value: "CharacterArmature|Idle",
      options: Object.keys(actions),
    },
  });

  useEffect(() => {
    actions[animation].reset().fadeIn(0.5).play();
    return () => actions[animation].fadeOut(0.5);
  }, [animation]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group
            name="CharacterArmature"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <primitive object={nodes.Root} />
          </group>
          <group
            name="Enemy_Robot_2Legs"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <skinnedMesh
              castShadow
              receiveShadow
              name="Enemy_Robot_2Legs_1"
              geometry={nodes.Enemy_Robot_2Legs_1.geometry}
              material={materials.Main2}
              skeleton={nodes.Enemy_Robot_2Legs_1.skeleton}
            />
            <skinnedMesh
              castShadow
              receiveShadow
              name="Enemy_Robot_2Legs_2"
              geometry={nodes.Enemy_Robot_2Legs_2.geometry}
              material={materials.Main}
              skeleton={nodes.Enemy_Robot_2Legs_2.skeleton}
            />
            <skinnedMesh
              castShadow
              receiveShadow
              name="Enemy_Robot_2Legs_3"
              geometry={nodes.Enemy_Robot_2Legs_3.geometry}
              material={materials.Edge}
              skeleton={nodes.Enemy_Robot_2Legs_3.skeleton}
            />
            <skinnedMesh
              castShadow
              receiveShadow
              name="Enemy_Robot_2Legs_4"
              geometry={nodes.Enemy_Robot_2Legs_4.geometry}
              material={materials.Dark}
              skeleton={nodes.Enemy_Robot_2Legs_4.skeleton}
            />
            <skinnedMesh
              castShadow
              receiveShadow
              name="Enemy_Robot_2Legs_5"
              geometry={nodes.Enemy_Robot_2Legs_5.geometry}
              material={materials.Eye}
              skeleton={nodes.Enemy_Robot_2Legs_5.skeleton}
            />
          </group>
          <group
            visible={false} // Hide the cylinder
            name="Cylinder"
            position={[0, 0.754, 0.002]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={13.18}
          >
            <skinnedMesh
              name="Cylinder_1"
              geometry={nodes.Cylinder_1.geometry}
              material={materials.Grey}
              skeleton={nodes.Cylinder_1.skeleton}
            />
            <skinnedMesh
              name="Cylinder_2"
              geometry={nodes.Cylinder_2.geometry}
              material={materials.LightGrey}
              skeleton={nodes.Cylinder_2.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("./models/enemies/Enemy.glb");
