/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { atom, useAtom } from "jotai";
import * as THREE from "three";
import { useFrame } from "@react-three/fiber";
import { lookAtPanel, newShootTarget } from "./ShootPanel";
export const triggerPosition = atom();

export function GunModel(props) {
  const { nodes, materials } = useGLTF("./models/gun/Gun.glb");
  const [newTriggerPosition, setNewTriggerPosition] = useAtom(triggerPosition);
  const [shootTarget] = useAtom(newShootTarget);
  const [lookAtPanelPosition] = useAtom(lookAtPanel);

  const trigger = useRef();
  const gunRef = useRef();

  useEffect(() => {
    setNewTriggerPosition(
      trigger.current.getWorldPosition(new THREE.Vector3())
    );
  }, []);

  useEffect(() => {
    if (!shootTarget) return;
    const worldPosition = trigger.current.getWorldPosition(new THREE.Vector3());

    setNewTriggerPosition(
      new THREE.Vector3(worldPosition.x, worldPosition.y, worldPosition.z)
    );
    console.log(
      trigger.current.getWorldPosition(new THREE.Vector3()),
      newTriggerPosition
    );
  }, [shootTarget]);

  useFrame(() => {
    gunRef.current.lookAt(lookAtPanelPosition);
  });

  return (
    <group {...props} dispose={null} ref={gunRef}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group265768751.geometry}
        material={materials.mat21}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1538806949.geometry}
        material={materials.mat23}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1322845791.geometry}
        material={materials.mat21}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1372893271.geometry}
        material={materials.mat5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1494860363.geometry}
        material={materials.mat23}
        // aqui
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1461796081.geometry}
        material={materials.mat17}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group684696646.geometry}
        material={materials.mat5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1229759417.geometry}
        material={materials.mat5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group507792610.geometry}
        material={materials.mat23}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1606866373.geometry}
        material={materials.mat23}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group110904487.geometry}
        material={materials.mat23}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1093921766.geometry}
        material={materials.mat23}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1110261251.geometry}
        material={materials.mat23}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1638908236.geometry}
        material={materials.mat5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group853773516.geometry}
        material={materials.mat21}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group616640639.geometry}
        material={materials.mat22}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1521711407.geometry}
        material={materials.mat5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1009416700.geometry}
        material={materials.mat21}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group434935618.geometry}
        material={materials.mat21}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group643093882.geometry}
        material={materials.mat5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1498746877.geometry}
        material={materials.mat23}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group2146565209.geometry}
        material={materials.mat21}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group773604818.geometry}
        material={materials.mat21}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group567611965.geometry}
        material={materials.mat5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group701822275.geometry}
        material={materials.mat21}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1945880488.geometry}
        material={materials.mat23}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1023070226.geometry}
        material={materials.mat24}
        // visible={false}
        ref={trigger}
        //!! este es
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1965182514.geometry}
        material={materials.mat24}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1524686534.geometry}
        material={materials.mat24}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1264047441.geometry}
        material={materials.mat24}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group298231118.geometry}
        material={materials.mat24}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group843406000.geometry}
        material={materials.mat24}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group94073891.geometry}
        material={materials.mat24}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1851450152.geometry}
        material={materials.mat5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1790223731.geometry}
        material={materials.mat23}
      />
    </group>
  );
}

useGLTF.preload("./models/gun/Gun.glb");
